\note{\tiny{All I have to do is look at the data and get the up-to-date version.  Then I look at how the analysis was done, and do it again on the new data.  Finally I look at how the analysis was presented, and I copy the relevent bits of data and analysis into a new version of the presentation and send it off.  So that was reproducible analysis, wasn't it?

Nope.  When I try to get the up-to-date data, I get slightly different numbers, because it turns out there was a little bit of tweaking done between the database and the spreadsheet.  And then a bit more tweaking done in the spreadsheet, saved over the top.

Then the analysis isn't quite consistent.  There's a column of formulae that I assume are all the same, except that one of the formulae part-way down is slightly different to cover a special case in the data.  And there's nothing to explain what the special case is, or how the formula handles it.  And anyway, the up-to-date data has a couple more special cases that need to be handled in the same way, which means I need to type that special formula in somewhere else, too.

Once I've sorted out all the data, and all the analysis, and I get to the presentation.  I copy the relevant bit from the analysis and paste it into the report, or the powerpoint, or whatever it is, and it doesn't fit.  It's too big now.  So I spend forever adjusting everything to fit.

Finally I send out the presentation, and straight away I get an email back that says, "Hey, that was the March presentation.  This is April".  What have I done?  I've forgotten to change the title at the top.  Or if it's going to Joe Public, Joe Public writes back to complain that, in order to exercise his democratic right to information, he has to buy spreadsheet software from an American business.}}

### Clean

Slide text.

### Second Slide

Something Here